version: '3.7'

services:
   postgres:
      container_name: nest-clean-pg
      image: postgres
      ports:
         - 5432:5432
      environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=docker
         - POSTGRES_DB=nest-question
         - PGDATA=/data/postgres
      volumes:
         - ./data/postgres:/var/lib/postgresql/data
